### ISSUE TITLE
Jekyll 博客美化：添加评论系统、侧边栏目录与中文字数统计 - My-Thistledown | Blog

### ISSUE THREAD

**Issue by Fang-Lansheng** [Fang-Lansheng/my-thistledown#4]
https://my-thistledown.com/2019/01/06/Making-blog-look-better/ 

 A Learner's Blog

**Comment by zhaoolee** [comment]
ok

**Comment by silvermissile** [comment]
侧边栏目录,只能显示两级，对应markdown的三四级标题，能不能显示多级呢？？？

**Comment by Fang-Lansheng** [comment]
> @silvermissile
> 侧边栏目录,只能显示两级，对应markdown的三四级标题，能不能显示多级呢？？？ 

可以显示多级标题，取决于 Markdown 中你的标题分级。我看到你也在使用 Huxpro 的模板，作者在 `less/side-catalog.less` 文件中设置了标题样式为：
```less
.h1_nav,.h2_nav,.h3_nav{
	margin-left: 0;
	font-size: 13px;
	font-weight: bold;
}
.h4_nav,.h5_nav,.h6_nav{
	margin-left: 10px;
	font-size: 12px;
	a{
		max-width: 170px;
	}
}
```
因此 h1、h2、h3 与 h4、h5、h6 分别使用的是相同的样式，所以显示出来只有两级标题。你可以自行修改相关代码，以达到自己满意的效果。
